# Generated by Django 6.0.1 on 2026-01-09 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('attender', 'Interview Attender'), ('taker', 'Interview Taker')], max_length=20, null=True)),
                ('linkedin_id', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_profile_url', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('current_position', models.CharField(blank=True, max_length=100)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('is_verified_expert', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
