# Generated by Django 6.0.1 on 2026-01-09 10:09

from django.db import migrations

def create_default_roles(apps, schema_editor):
    Role = apps.get_model('profiles', 'Role')
    
    # Delete old roles first
    Role.objects.all().delete()
    
    # Create only attender and taker roles
    roles_data = [
        {
            'name': 'attender',
            'description': 'Interview Attender - Can attend interviews and send interview requests.',
        },
        {
            'name': 'taker', 
            'description': 'Interview Taker - Can conduct interviews and receive interview requests.',
        }
    ]
    
    for role_data in roles_data:
        Role.objects.get_or_create(
            name=role_data['name'],
            defaults={
                'description': role_data['description'],
                'permissions': {},
                'is_active': True
            }
        )

def reverse_create_default_roles(apps, schema_editor):
    Role = apps.get_model('profiles', 'Role')
    Role.objects.filter(name__in=['attender', 'taker']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_role_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_roles, reverse_create_default_roles),
    ]
