# Generated by Django 6.0.1 on 2026-01-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20260109_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('attender', 'Interview Attender'), ('taker', 'Interview Taker')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('attender', 'Interview Attender'), ('taker', 'Interview Taker')], max_length=20, null=True),
        ),
    ]
