# Generated by Django 6.0.1 on 2026-01-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_add_multi_role_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='career_goals',
            field=models.TextField(blank=True, help_text='Career goals and aspirations'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expertise_areas',
            field=models.JSONField(blank=True, default=list, help_text='List of expertise areas (e.g., ["Python", "System Design", "Machine Learning"])'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interviewing_experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Years of experience conducting interviews'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_steps_completed',
            field=models.JSONField(blank=True, default=dict, help_text='Tracks completion of each onboarding section'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_interview_domains',
            field=models.JSONField(blank=True, default=list, help_text='Preferred interview domains (e.g., ["Backend", "Frontend", "Data Science"])'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Resume/profile metadata (text-based, no file upload)'),
        ),
    ]
