# Generated by Django 6.0.1 on 2026-01-20 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_add_onboarding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='available_time_slots',
            field=models.JSONField(blank=True, default=list, help_text='Available time slots for interviews in JSON format'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(blank=True, help_text='Current job title/designation', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='Mobile number with country code (e.g., +91-9876543210)', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief professional bio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='career_goals',
            field=models.TextField(blank=True, help_text='DEPRECATED: Use IntervieweeProfile.career_goal instead'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Total years of professional experience'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='expertise_areas',
            field=models.JSONField(blank=True, default=list, help_text='DEPRECATED: Use InterviewerProfile.expertise_areas instead'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interviewing_experience_years',
            field=models.PositiveIntegerField(default=0, help_text='DEPRECATED: Use InterviewerProfile instead'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='onboarding_steps_completed',
            field=models.JSONField(blank=True, default=dict, help_text='Tracks completion of each onboarding section: {"common": True, "interviewer": True, "interviewee": False}'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_interview_domains',
            field=models.JSONField(blank=True, default=list, help_text='DEPRECATED: Use IntervieweeProfile instead'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='resume_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='DEPRECATED: Use IntervieweeProfile instead'),
        ),
        migrations.CreateModel(
            name='IntervieweeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField(blank=True, default=list, help_text='Skills with proficiency levels: [{"skill": "Python", "level": "expert"}]')),
                ('target_role', models.CharField(blank=True, help_text='Target job role (e.g., "Senior Software Engineer")', max_length=100)),
                ('preferred_interview_language', models.CharField(blank=True, help_text='Preferred language for conducting interviews (e.g., "English", "Hindi")', max_length=50)),
                ('career_goal', models.CharField(blank=True, choices=[('finding_jobs', 'Finding Jobs'), ('switching_jobs', 'Switching Jobs')], help_text='Career goal: finding jobs or switching jobs', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interviewee_profile', to='profiles.userprofile')),
            ],
            options={
                'verbose_name': 'Interviewee Profile',
                'verbose_name_plural': 'Interviewee Profiles',
            },
        ),
        migrations.CreateModel(
            name='InterviewerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise_areas', models.JSONField(blank=True, default=list, help_text='Expertise areas with levels: [{"area": "System Design", "level": "expert"}]')),
                ('credits_per_interview', models.PositiveIntegerField(default=0, help_text='Number of credits charged per interview session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_profile', to='profiles.userprofile')),
            ],
            options={
                'verbose_name': 'Interviewer Profile',
                'verbose_name_plural': 'Interviewer Profiles',
            },
        ),
    ]
