# Generated by Django 6.0.1 on 2026-01-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_onboarding_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewerprofile',
            name='interviewing_experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Years of experience conducting interviews'),
        ),
        migrations.AddField(
            model_name='interviewerprofile',
            name='linkedin_profile_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL for verification'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, help_text="User's preferred display name", max_length=100),
        ),
    ]
