# Generated by Django 6.0.1 on 2026-01-20 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_rename_display_name_to_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_verified_expert',
        ),
    ]
