# Generated by Django 6.0.1 on 2026-01-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_remove_verified_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_prefix',
            field=models.CharField(blank=True, default='', help_text='Phone number country code prefix (e.g., +91, +1, +44)', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='Mobile number without country code (e.g., 9876543210)', max_length=20),
        ),
    ]
