# Generated by Django 6.0.1 on 2026-01-22 05:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_add_phone_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='public_id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
