# Generated by Django 6.0.1 on 2026-01-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_userprofile_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, help_text='Current company/organization name', max_length=150),
        ),
    ]
