# Generated by Django 6.0.1 on 2026-01-23 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_add_company_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified_user',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether user is a verified expert (via LinkedIn or admin)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_company',
            field=models.CharField(blank=True, default='', help_text='Company from LinkedIn profile', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_experience_years',
            field=models.PositiveIntegerField(blank=True, help_text='Years of experience from LinkedIn profile', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_full_name',
            field=models.CharField(blank=True, default='', help_text='Full name from LinkedIn profile', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_headline',
            field=models.CharField(blank=True, default='', help_text='Headline from LinkedIn profile', max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_notes',
            field=models.TextField(blank=True, default='', help_text='Admin notes about verification'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the user was verified', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin who verified this user (if verified_via=admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verified_via',
            field=models.CharField(blank=True, choices=[('linkedin', 'LinkedIn'), ('admin', 'Admin Manual Verification')], help_text='How the user was verified: linkedin, admin, or null', max_length=20, null=True),
        ),
    ]
