# Generated by Django 6.0.1 on 2026-01-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_userprofile_is_verified_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_email',
            field=models.EmailField(blank=True, help_text='Email address from LinkedIn OAuth (may differ from user email)', max_length=254, null=True),
        ),
    ]
