# Generated by Django 6.0.1 on 2026-02-05 03:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0004_alter_interviewauditlog_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TakerEarnings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_earned', models.PositiveIntegerField(default=0, help_text='Total credits earned from interviews')),
                ('pending_credits', models.PositiveIntegerField(default=0, help_text='Credits pending feedback submission')),
                ('interviews_completed', models.PositiveIntegerField(default=0, help_text='Total number of interviews completed')),
                ('feedbacks_submitted', models.PositiveIntegerField(default=0, help_text='Total number of feedbacks submitted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taker_earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Taker Earnings',
                'verbose_name_plural': 'Taker Earnings',
            },
        ),
        migrations.CreateModel(
            name='AttenderFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating 1-5: Overall interview experience', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('professionalism', models.PositiveSmallIntegerField(blank=True, help_text='Rating 1-5: How professional was the interviewer?', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('question_clarity', models.PositiveSmallIntegerField(blank=True, help_text='Rating 1-5: How clear were the interview questions?', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback_helpfulness', models.PositiveSmallIntegerField(blank=True, help_text='Rating 1-5: How helpful was the feedback received?', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True, default='', help_text='Additional comments about the interview experience')),
                ('would_recommend', models.BooleanField(blank=True, help_text='Would you recommend this interviewer to others?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_feedback', to=settings.AUTH_USER_MODEL)),
                ('interview_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attender_feedback', to='interviews.interviewrequest')),
            ],
            options={
                'verbose_name': 'Attender Feedback',
                'verbose_name_plural': 'Attender Feedback',
                'indexes': [models.Index(fields=['interview_request'], name='credits_att_intervi_2141b1_idx'), models.Index(fields=['attender'], name='credits_att_attende_142ec7_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreditBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.PositiveIntegerField(default=0, help_text='Current available credit balance', validators=[django.core.validators.MinValueValidator(0)])),
                ('escrow_balance', models.PositiveIntegerField(default=0, help_text='Credits held in escrow for pending/accepted interviews', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_earned', models.PositiveIntegerField(default=0, help_text='Total credits ever received (including initial)')),
                ('total_spent', models.PositiveIntegerField(default=0, help_text='Total credits ever spent on interviews')),
                ('has_received_initial_credits', models.BooleanField(default=False, help_text='Whether user has received the 1000 initial signup credits')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Balance',
                'verbose_name_plural': 'Credit Balances',
                'indexes': [models.Index(fields=['user'], name='credits_cre_user_id_93f943_idx'), models.Index(fields=['balance'], name='credits_cre_balance_5a1d10_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('initial_credit', 'Initial Credit (Signup Bonus)'), ('interview_debit', 'Interview Debit (Escrow)'), ('interview_credit', 'Interview Credit (Taker Payout)'), ('refund', 'Refund'), ('admin_adjustment', 'Admin Adjustment')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('amount', models.IntegerField(help_text='Transaction amount (positive=credit, negative=debit)')),
                ('balance_after', models.PositiveIntegerField(help_text='Balance after this transaction was applied')),
                ('description', models.TextField(blank=True, default='', help_text='Human-readable description of the transaction')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional transaction metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User/Admin who initiated this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credit_transactions', to=settings.AUTH_USER_MODEL)),
                ('interview_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='interviews.interviewrequest')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_transactions', to='credits.credittransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='credits_cre_user_id_6943f8_idx'), models.Index(fields=['interview_request'], name='credits_cre_intervi_1c3c81_idx'), models.Index(fields=['transaction_type', 'status'], name='credits_cre_transac_3bf5ad_idx'), models.Index(fields=['status'], name='credits_cre_status_f6cbdf_idx')],
            },
        ),
        migrations.CreateModel(
            name='TakerFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('submitted', 'Submitted'), ('rejected', 'Rejected')], default='not_submitted', max_length=20)),
                ('technical_knowledge', models.PositiveSmallIntegerField(blank=True, help_text='Rating 1-5: How well did the candidate demonstrate technical knowledge?', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_skills', models.PositiveSmallIntegerField(blank=True, help_text='Rating 1-5: How effectively did the candidate communicate?', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('problem_solving', models.PositiveSmallIntegerField(blank=True, help_text='Rating 1-5: How well did the candidate approach and solve problems?', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('overall_performance', models.PositiveSmallIntegerField(blank=True, help_text='Rating 1-5: Overall interview performance rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('detailed_feedback', models.TextField(blank=True, default='', help_text='Detailed written feedback about the candidate (required for submission)')),
                ('strengths', models.TextField(blank=True, default='', help_text='Key strengths observed during the interview')),
                ('areas_for_improvement', models.TextField(blank=True, default='', help_text='Areas where the candidate can improve')),
                ('would_hire', models.BooleanField(blank=True, help_text='Would you recommend hiring this candidate?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('interview_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taker_feedback', to='interviews.interviewrequest')),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Taker Feedback',
                'verbose_name_plural': 'Taker Feedback',
                'indexes': [models.Index(fields=['interview_request', 'status'], name='credits_tak_intervi_c254a1_idx'), models.Index(fields=['taker', 'status'], name='credits_tak_taker_i_34d89a_idx')],
            },
        ),
    ]
