# Generated by Django 6.0.1 on 2026-02-05 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attenderfeedback',
            name='credits_att_intervi_2141b1_idx',
        ),
        migrations.RemoveIndex(
            model_name='attenderfeedback',
            name='credits_att_attende_142ec7_idx',
        ),
        migrations.RemoveIndex(
            model_name='takerfeedback',
            name='credits_tak_intervi_c254a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='takerfeedback',
            name='credits_tak_taker_i_34d89a_idx',
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who initiated this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credit_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('initial_credit', 'Initial Credit (Signup Bonus)'), ('interview_debit', 'Interview Debit (Escrow)'), ('interview_credit', 'Interview Credit (Taker Payout)'), ('refund', 'Refund')], max_length=30),
        ),
        migrations.RemoveField(
            model_name='takerfeedback',
            name='interview_request',
        ),
        migrations.RemoveField(
            model_name='takerfeedback',
            name='taker',
        ),
        migrations.DeleteModel(
            name='AttenderFeedback',
        ),
        migrations.DeleteModel(
            name='TakerFeedback',
        ),
    ]
