# Generated by Django 6.0.1 on 2026-01-23 05:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def generate_uuid_for_existing_records(apps, schema_editor):
    """Generate UUIDs for existing interview requests."""
    InterviewRequest = apps.get_model('interviews', 'InterviewRequest')
    for request in InterviewRequest.objects.all():
        request.uuid_id = uuid.uuid4()
        request.save(update_fields=['uuid_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Add a temporary UUID field
        migrations.AddField(
            model_name='interviewrequest',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        
        # Step 2: Populate UUID for existing records
        migrations.RunPython(generate_uuid_for_existing_records, migrations.RunPython.noop),
        
        # Step 3: Add new fields to InterviewRequest
        migrations.AddField(
            model_name='interviewrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewrequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewrequest',
            name='credits',
            field=models.PositiveIntegerField(default=0, help_text='Credits for this interview (from interviewer profile)'),
        ),
        migrations.AddField(
            model_name='interviewrequest',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Interview duration in minutes'),
        ),
        migrations.AddField(
            model_name='interviewrequest',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewrequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for rejection or cancellation'),
        ),
        migrations.AddField(
            model_name='interviewrequest',
            name='topic',
            field=models.CharField(blank=True, default='', help_text='Interview topic or focus area', max_length=200),
        ),
        migrations.AddField(
            model_name='interviewrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Step 4: Alter other fields
        migrations.AlterModelOptions(
            name='interviewrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='interviewrequest',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='interviewrequest',
            name='message',
            field=models.TextField(blank=True, default='', help_text='Optional message from sender to receiver'),
        ),
        migrations.AlterField(
            model_name='interviewrequest',
            name='receiver',
            field=models.ForeignKey(help_text='User who receives the request (must be TAKER)', on_delete=django.db.models.deletion.CASCADE, related_name='received_interview_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interviewrequest',
            name='scheduled_time',
            field=models.DateTimeField(help_text='Scheduled date and time for the interview'),
        ),
        migrations.AlterField(
            model_name='interviewrequest',
            name='sender',
            field=models.ForeignKey(help_text='User who sent the request (must be ATTENDER)', on_delete=django.db.models.deletion.CASCADE, related_name='sent_interview_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interviewrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20),
        ),
        
        # Step 5: Create new models that reference InterviewRequest via uuid_id instead of id
        migrations.CreateModel(
            name='InterviewAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('expired', 'Expired'), ('joined', 'Joined Room'), ('left', 'Left Room'), ('admin_override', 'Admin Override')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional action details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='interviews.interviewrequest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveKitRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(db_index=True, help_text='LiveKit room name (format: interview-{uuid})', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the room is currently active')),
                ('sender_joined_at', models.DateTimeField(blank=True, null=True)),
                ('receiver_joined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('interview_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livekit_room', to='interviews.interviewrequest')),
            ],
            options={
                'verbose_name': 'LiveKit Room',
                'verbose_name_plural': 'LiveKit Rooms',
            },
        ),
        
        # Step 6: Add indexes
        migrations.AddIndex(
            model_name='interviewauditlog',
            index=models.Index(fields=['interview_request', 'action'], name='interviews__intervi_0e8a77_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewauditlog',
            index=models.Index(fields=['user', 'action'], name='interviews__user_id_c35071_idx'),
        ),
    ]
