# Generated by Django 6.0.1 on 2026-01-24 08:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewauditlog_livekitroom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewTimeOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposed_time', models.DateTimeField(db_index=True, help_text='Proposed interview time')),
                ('is_selected', models.BooleanField(default=False, help_text='Whether this time option was selected by the taker')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['proposed_time'],
            },
        ),
        migrations.AlterField(
            model_name='interviewrequest',
            name='uuid_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='UUID for API-safe exposure', unique=True),
        ),
        migrations.AddIndex(
            model_name='interviewrequest',
            index=models.Index(fields=['sender', 'receiver', 'status'], name='interviews__sender__09282d_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewrequest',
            index=models.Index(fields=['status', 'scheduled_time'], name='interviews__status_c12ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewrequest',
            index=models.Index(fields=['receiver', 'status'], name='interviews__receive_f27480_idx'),
        ),
        migrations.AddField(
            model_name='interviewtimeoption',
            name='interview_request',
            field=models.ForeignKey(help_text='Interview request this time option belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='time_options', to='interviews.interviewrequest'),
        ),
        migrations.AddIndex(
            model_name='interviewtimeoption',
            index=models.Index(fields=['interview_request', 'is_selected'], name='interviews__intervi_8a0990_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewtimeoption',
            index=models.Index(fields=['proposed_time'], name='interviews__propose_b5142a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewtimeoption',
            unique_together={('interview_request', 'proposed_time')},
        ),
    ]
