# Generated by Django 6.0.1 on 2026-02-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_interviewtimeoption_alter_interviewrequest_uuid_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('not_attended', 'Not Attended'), ('expired', 'Expired'), ('joined', 'Joined Room'), ('left', 'Left Room'), ('admin_override', 'Admin Override')], max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('not attended', 'Not attended')], db_index=True, default='pending', max_length=20),
        ),
    ]
