# Generated by Django 6.0.1 on 2026-02-05 04:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_alter_interviewauditlog_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewerFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted')], db_index=True, default='pending', help_text='Current submission status', max_length=20)),
                ('problem_understanding_rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating 1-5: How well did the candidate understand the problem?', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('problem_understanding_text', models.TextField(blank=True, default='', help_text='Explanation of problem understanding assessment')),
                ('solution_approach_rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating 1-5: How effective was the solution approach?', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('solution_approach_text', models.TextField(blank=True, default='', help_text='Explanation of solution approach assessment')),
                ('implementation_skill_rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating 1-5: How well did candidate implement the solution?', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('implementation_skill_text', models.TextField(blank=True, default='', help_text='Explanation of implementation skill assessment')),
                ('communication_rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating 1-5: How well did the candidate communicate?', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_text', models.TextField(blank=True, default='', help_text='Explanation of communication assessment')),
                ('overall_feedback', models.TextField(blank=True, default='', help_text='Overall feedback and final thoughts (required for submission)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Timestamp when feedback was submitted', null=True)),
                ('interview_request', models.OneToOneField(help_text='The interview this feedback belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_feedback', to='interviews.interviewrequest')),
                ('interviewer', models.ForeignKey(help_text='The taker who submitted this feedback', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interviewer Feedback',
                'verbose_name_plural': 'Interviewer Feedbacks',
                'db_table': 'interviews_interviewer_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='interviews__status_8c8106_idx'), models.Index(fields=['interviewer', 'status'], name='interviews__intervi_52653a_idx')],
            },
        ),
    ]
