# Generated by Django 6.0.1 on 2026-02-05 04:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_interviewerfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_experience_rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating 1-5: How was your overall interview experience?', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('professionalism_rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating 1-5: How professional was the interviewer?', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('question_clarity_rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating 1-5: How clear were the interview questions?', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback_quality_rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating 1-5: How helpful was the feedback you received?', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True, default='', help_text='Additional comments about your interview experience (optional)')),
                ('would_recommend', models.BooleanField(blank=True, help_text='Would you recommend this interviewer to others?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(help_text='The attender who submitted this feedback', on_delete=django.db.models.deletion.CASCADE, related_name='given_candidate_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('interview_request', models.OneToOneField(help_text='The interview this feedback belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='candidate_feedback', to='interviews.interviewrequest')),
            ],
            options={
                'verbose_name': 'Candidate Feedback',
                'verbose_name_plural': 'Candidate Feedbacks',
                'db_table': 'interviews_candidate_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['candidate', 'created_at'], name='interviews__candida_811412_idx')],
            },
        ),
    ]
