# Generated by Django 6.0.1 on 2026-02-06 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_add_candidate_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='interviewerfeedback',
            constraint=models.UniqueConstraint(fields=('interview_request', 'interviewer'), name='unique_interviewer_feedback'),
        ),
    ]
