# Generated by Django 6.0.1 on 2026-02-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0008_add_attendance_tracking_and_not_conducted_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('not_attended', 'Not Attended'), ('not_conducted', 'Not Conducted'), ('expired', 'Expired'), ('joined', 'Joined Room'), ('left', 'Left Room'), ('admin_override', 'Admin Override')], max_length=20),
        ),
    ]
