# Generated by Django 6.0.1 on 2026-02-03 05:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0004_alter_interviewauditlog_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('interview_created', 'Interview Created'), ('interview_accepted', 'Interview Accepted'), ('interview_rejected', 'Interview Rejected'), ('interview_completed', 'Interview Completed'), ('interview_not_attended', 'Interview Not Attended'), ('interview_cancelled', 'Interview Cancelled')], db_index=True, help_text='Type of notification', max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message/body')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional notification data in JSON format')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether the notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered this notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('interview_request', models.ForeignKey(blank=True, help_text='Related interview request', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='interviews.interviewrequest')),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['recipient', 'notification_type'], name='notificatio_recipie_028906_idx')],
            },
        ),
    ]
